### ISSUE TITLE
Release 1.9.8 version

### ISSUE THREAD

**Issue by mjcctech** [LaurentGoderre/docker-pachctl#2]
Could you be so kind and release 1.9.8 version.

**Comment by LaurentGoderre** [comment]
Absolutely! Will do tonight!

**Comment by mjcctech** [comment]
I'm looking forward. In mean time version 1.9.9 was just published.

**Comment by LaurentGoderre** [comment]
For some reason, the alpine version built fine but the debian version doesn't seem to work.

**Comment by LaurentGoderre** [comment]
I published all the version but only the alpine ones because debian doesn't build in the most recent one.

**Comment by mjcctech** [comment]
Many thanks!
